<?php

namespace AppBundle\Repository;

/**
 * cursosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class cursosRepository extends \Doctrine\ORM\EntityRepository
{
}
