<?php

namespace AppBundle\Repository;

/**
 * telefonoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class telefonoRepository extends \Doctrine\ORM\EntityRepository
{
}
